# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20170111_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='license_status',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
