# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20170111_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='milestone',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='milestone_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
