# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20170118_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='home_based',
            field=models.NullBooleanField(db_index=True),
        ),
    ]
