# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20170118_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='district',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='license_active',
            field=models.NullBooleanField(db_index=True),
        ),
    ]
