# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20170118_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_year',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
