# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographic', '0007_feature_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='dist_lbpd',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='dist_park',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
