# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographic', '0012_auto_20170112_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='dist_bike',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
