# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date_occured',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The date and time of the incident.', null=True),
        ),
    ]
