# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0003_auto_20170111_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='magnitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
