# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='filename',
        ),
        migrations.AddField(
            model_name='parcel',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
