# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_auto_20170110_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='number',
            new_name='objectid',
        ),
    ]
