# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 23:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_auto_20170110_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, db_index=True, null=True, srid=4326),
        ),
    ]
